establish app and sdk package isolation with core submodule (#347)
* establish app and sdk package isolation with core submodule (these can all move)

* use remote kuneiform

* workspace mode in CI

* tweaks and docs

* moving config / nodecfg around; still not great

* auth docs, but can't move the authenticators

* doc typo fix

diff --git a/scripts/mods/check_tidy b/scripts/mods/check_tidy
--- a/scripts/mods/check_tidy
+++ b/scripts/mods/check_tidy
@@ -1,13 +1,28 @@
 #!/usr/bin/env bash
 
-go mod tidy
+set -e
 
-STATUS=$(git status go.mod go.sum --porcelain)
+modules=("./core" "./parse" "." "./test")
 
-if [[ -n "$STATUS" ]]; then
-    echo "Changes detected in 'go.mod' or 'go.sum' after running 'go mod tidy'!"
-    exit 1
-else
-    echo "No changes detected in 'go.mod' or 'go.sum'."
-    exit 0
-fi
+for mod in "${modules[@]}"; do
+    pushd "$dir" > /dev/null || {
+        echo "Could not change to directory: $mod"
+        exit 1
+    }
+
+    go mod tidy
+
+    STATUS=$(git status go.mod go.sum --porcelain)
+
+    if [[ -n "$STATUS" ]]; then
+        echo "Changes detected in 'go.mod' or 'go.sum' after running 'go mod tidy' in module $mod!"
+        popd > /dev/null
+        exit 1
+    else
+        echo "No changes detected in 'go.mod' or 'go.sum' in module $mod."
+    fi
+
+    popd > /dev/null
+done
+
+exit 0
